#!/bin/sh
# Script to install preload.conf

PREFIX=${PKG_PREFIX-/usr/local}

if [ "$2" != "POST-INSTALL" ] ; then
   exit 0
fi

# If this is during staging, we can skip for now
echo $PREFIX | grep -q '/stage/'
if [ $? -eq 0 ] ; then
   exit 0
fi

# Copy over customizations for TrueOS
  install -m 644 ${PREFIX}/share/trueos/conf/loader.conf.trueos /boot/loader.conf.trueos
  install -m 644 ${PREFIX}/share/trueos/conf/brand-trueos.4th /boot/brand-trueos.4th

if [ ! -e "${PREFIX}/etc/trueos.conf" ] ; then
  # Do the first-time setup
  echo "Doing first-time bootstrap"
  if [ -e "/etc/defaults/trueos-desktop" ] ; then
    tar cvf - -C ${PREFIX}/share/trueos/desktop-defaults/ . 2>/dev/null | tar xvf - -C / 2>/dev/null
    /sbin/rc-update add ipfw boot
    /sbin/rc-update add dhcpcd default
    /sbin/rc-update add wpa_supplicant default
    /sbin/rc-update add openntpd default
    /sbin/rc-update add pcdm default
  else
    tar cvf - -C ${PREFIX}/share/trueos/server-defaults/ . 2>/dev/null | tar xvf - -C / 2>/dev/null
    /sbin/rc-update add ipfw boot
    /sbin/rc-update add dhcpcd default
    /sbin/rc-update add wpa_supplicant default
  fi
fi

exit 0
