#!/bin/sh
# Script to install preload.conf

PREFIX=${PKG_PREFIX-/usr/local}

if [ "$2" != "POST-INSTALL" ] ; then
   exit 0
fi

set +e

# If this is during staging, we can skip for now
echo $PREFIX | grep -q '/stage/'
if [ $? -eq 0 ] ; then
   exit 0
fi


# Enable the OpenRC services

if [ ! -e "/var/.openrc-migrate-1" ] ; then
  /sbin/rc-update add devd boot >/dev/null 2>/dev/null
  /sbin/rc-update add routing boot >/dev/null 2>/dev/null
  /sbin/rc-update delete dhcpcd default >/dev/null 2>/dev/null
  /sbin/rc-update delete wpa_supplicant default >/dev/null 2>/dev/null
  /sbin/rc-update add sysadm default >/dev/null 2>/dev/null
  /sbin/rc-update add bsdstats default >/dev/null 2>/dev/null
fi
touch /var/.openrc-migrate-1

if [ ! -e "/var/.openrc-migrate-3" ] ; then
  if [ -e "/etc/conf.d/modules" ] ; then
    cat /etc/conf.d/modules | grep -v "modules=" > /etc/conf.d/modules.new
    mv /etc/conf.d/modules.new /etc/conf.d/modules
    chmod 755 /etc/conf.d/modules
  fi
fi
touch /var/.openrc-migrate-3

if [ ! -e "/var/.openrc-migrate-4" ] ; then
    /sbin/rc-update add mountlate default >/dev/null 2>/dev/null
fi
touch /var/.openrc-migrate-4

exit 0
