#!/bin/sh
# Script to install preload.conf

PREFIX=${PKG_PREFIX-/usr/local}

if [ "$2" != "POST-INSTALL" ] ; then
   exit 0
fi

# If this is during staging, we can skip for now
echo $PREFIX | grep -q '/stage/'
if [ $? -eq 0 ] ; then
   exit 0
fi

# Copy over customizations for TrueOS
  install -m 644 ${PREFIX}/share/trueos/conf/brand-trueos.4th /boot/brand-trueos.4th
  install -m 644 ${PREFIX}/share/trueos/server-defaults/etc/conf.d/modules /etc/conf.d/modules/

if [ ! -e "${PREFIX}/etc/trueos.conf" ] ; then
  # Do the first-time setup
  echo "Doing first-time bootstrap"
  tar cvf - -C ${PREFIX}/share/trueos/server-defaults/ . 2>/dev/null | tar xvf - -C / 2>/dev/null
fi

# Enable the OpenRC services
set +e

if [ -e "/var/.openrc-migrate-1" ] ; then
  exit 0
fi

/sbin/rc-update add devd boot
/sbin/rc-update add routing boot
/sbin/rc-update delete dhcpcd default
/sbin/rc-update delete wpa_supplicant default
/sbin/rc-update add sysadm default

touch /var/.openrc-migrate-1

exit 0
